version: '3.3'

services:
  application:
    build: ./application
    ports:
      - "8181:8080"
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - payments
      - tokens
      - transactions
      - accounts
  payments:
    build: ./payments
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  transactions:
    build: ./transactions
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  tokens:
    build: ./tokens
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  accounts:
    build: ./accounts
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "alex"
      RABBITMQ_DEFAULT_PASS: "alex"

