version: '3.3'

services:
  application:
    build: ./application
    ports:
      - "8181:8080"
  payments:
    build: ./payments
  transactions:
    build: ./transactions
  tokens:
    build: ./tokens
  accounts:
    build: ./accounts
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "alex"
      RABBITMQ_DEFAULT_PASS: "alex"

